# conda environment file for python 3, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py3_conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: py3-ulmo

channels:
    - conda-forge
    - defaults

dependencies:
    - python>=3.4
    - appdirs
    - beautifulsoup4
    - future
    - geojson
    - isodate
    - lxml
    - mock
    - numpy
    - pandas
    - pytables
    - pytest
    - requests
    - suds-jurko
    - freezegun
    - html5lib<=0.9999999

    # test dependencies
    - pytest-runner
    - pytest-cov
    - coveralls

    - pip:
        - httpretty<=0.8.10